apiVersion: v1
kind: ConfigMap
metadata:
  name: store-db-config
  namespace: default
data:
  postgres_user: postgres
  postgres_password: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-db
spec:
  selector:
    matchLabels:
      app: store-db
  template:
    metadata:
      labels:
        app: store-db
    spec:
      volumes:
        - name: store-db-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: store-db
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: store-db-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: store-db-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: store-db
          volumeMounts:
            - name: store-db-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: store-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: store-db